name: Deploy to Test

on:
  push:
    branches: 'drupal9'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
        with:
          php-version: '7.4.22'
      - uses: actions/checkout@v2
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.ZONECREW_PRIVATE_RSA}}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.ZONECREW_HOST}} > ~/.ssh/known_hosts
          sudo chown 400 ~/.ssh/id_rsa
      - name: Copy Files (scp)
        run: |
          ssh ${{secrets.ZONECREW_SSH_USERNAME}}:'${{secrets.ZONECREW_SSH_PASSWORD}}'@${{secrets.ZONECREW_HOST}} "rm -fR /home1/zonecrew/test.spinheadmedia.com/modules"
          ssh ${{secrets.ZONECREW_SSH_USERNAME}}:'${{secrets.ZONECREW_SSH_PASSWORD}}'@${{secrets.ZONECREW_HOST}} "rm -fR /home1/zonecrew/test.spinheadmedia.com/themes"
          sshpass -p ${{secrets.ZONECREW_SSH_PASSWORD}} scp -ri ~/.ssh/id_rsa ./modules/* ${{secrets.ZONECREW_SSH_USERNAME}}@${{secrets.ZONECREW_HOST}}:/home1/zonecrew/test.spinheadmedia.com/modules/
          sshpass -p ${{secrets.ZONECREW_SSH_PASSWORD}} scp -ri ~/.ssh/id_rsa ./themes/* ${{secrets.ZONECREW_SSH_USERNAME}}@${{secrets.ZONECREW_HOST}}:/home1/zonecrew/test.spinheadmedia.com/themes/
